import pyautogui
import time

while True:
    pyautogui.PAUSE = 0.5

    # começando partida
    time.sleep(2)
    pyautogui.moveTo(x=505, y=617)
    pyautogui.click(x=505, y=617)
    time.sleep(2)
    pyautogui.moveTo(x=775, y=171)
    pyautogui.click(x=775, y=171)

    # Gerador de dinheiro
    time.sleep(22)
    pyautogui.moveTo(x=588, y=358)
    pyautogui.press("4")
    pyautogui.click(x=588, y=358)
    time.sleep(1)

    # Grift o dps da partida 
    time.sleep(22)
    pyautogui.moveTo(x=499, y=353)
    pyautogui.press("1")
    pyautogui.click(x=499, y=353)
    time.sleep(1)
    pyautogui.click(x=442, y=355)
    pyautogui.click(x=588, y=358)
    pyautogui.press("t")
    time.sleep(1)
    pyautogui.press("t")
    time.sleep(21)
    pyautogui.press("t")
    time.sleep(1)
    pyautogui.press("t")
    time.sleep(21)
    pyautogui.press("t")
    time.sleep(1)
    pyautogui.press("t")
    time.sleep(23)
    pyautogui.click(x=442, y=355)
    time.sleep(1)
    pyautogui.click(x=588, y=358)
    time.sleep(1)
    pyautogui.press("t")

    # Jinwu o protetor do cavaleiro
    time.sleep(2)
    pyautogui.moveTo(x=553, y=525)
    pyautogui.press("2")
    pyautogui.click(x=553, y=525)
    time.sleep(21)
    pyautogui.click(x=588, y=358)
    pyautogui.press("t")
    time.sleep(1)
    pyautogui.press("t")
    time.sleep(43)
    pyautogui.moveTo(x=553, y=525)
    pyautogui.press("2")
    pyautogui.click(x=553, y=525)
    pyautogui.click(x=588, y=358)
    pyautogui.press("t")
    time.sleep(1)
    pyautogui.press("t")
    pyautogui.press("t")
    pyautogui.press("t")


    # Caveiro a última esperança da partida
    time.sleep(3)
    pyautogui.moveTo(x=554, y=505)
    pyautogui.press("3")
    pyautogui.click(x=554, y=505)

    # Upando as peças etapa final
    time.sleep(5)
    pyautogui.click(x=553, y=525)
    pyautogui.press("t")
    pyautogui.press("t")
    pyautogui.press("t")
    pyautogui.press("t")
    time.sleep(10)
    pyautogui.press("t")
    pyautogui.press("t")
    time.sleep(25)
    pyautogui.click(x=554, y=505)
    pyautogui.press("t")
    pyautogui.press("t")
    pyautogui.press("t")
    pyautogui.press("t")
    time.sleep(25)
    pyautogui.press("t")
    pyautogui.press("t")
    pyautogui.press("t")
    pyautogui.press("t")
    pyautogui.press("t")
    pyautogui.press("t")
    pyautogui.press("t")
    time.sleep(20)
    pyautogui.click(x=553, y=525)
    pyautogui.press("t")
    pyautogui.press("t")
    pyautogui.press("t")
    time.sleep(300)
    pyautogui.click(x=969, y=464)
    time.sleep(1)
    pyautogui.click(x=969, y=464)
    time.sleep(1)
    pyautogui.click(x=969, y=464)
    time.sleep(1)
    pyautogui.click(x=969, y=464)
    time.sleep(1)

#---------------------------------------------------
